### ISSUE TITLE
UPDATE First and Last Name at next login

### ISSUE THREAD

**Issue by enricoeur81** [rtCamp/login-with-google#110]
Hello,

i'm observinng that plugin doesnt give possibility to update firstname and lastaname i ncase the user changed them on Gmail. Is it possible to add an ACTIOn HOOKUP to trigger after a login ?

In this way if needed we can run some updatting procedure also when the user account is already created, but maybe need to be updated.

Thanks

**Comment by aviral-mittal** [comment]
@abhishekfdd Please link the pull request and discuss the PHP test units related query as discussed.

**Comment by abhishekfdd** [comment]
@enricoeur81  Now first name and last name can be updated from google at subsequent login if required using this [hook](https://github.com/rtCamp/login-with-google/blob/3b6aa20ead4a5a2960d66f6f0987add63dfb069b/src/Utils/Authenticator.php#L72) here.
