### ISSUE TITLE
Make the plugin multisite compatible

### ISSUE THREAD

**Issue by aviral-mittal** [rtCamp/login-with-google#119]
## Issue Description

Need to make the plugin multisite compatible. As encountered [here](https://rtcamp.slack.com/archives/C7VFLQZLJ/p1660310949914039?thread_ts=1660306817.710329&cid=C7VFLQZLJ), the plugin is probably not multisite compatible as of now. 

Please investigate the same and if not, please make the plugin multisite compatible.

**Comment by abhishekfdd** [comment]
@aviral-mittal  Tested this on subdirectory multisite setup with version 1.2.2 currently on Wordpress [Repo](https://wordpress.org/plugins/login-with-google/)

**Comment by aviral-mittal** [comment]
@Rink9 Can you please test the last released version on multisite setup to check if any problems are being faced?

**Comment by Rink9** [comment]
@abhishekfdd I have activated Login with Google plugin on my multisite. And also setup the steps mentioned on [here](https://wordpress.org/plugins/login-with-google/). But still it's not working and getting this error.
Sharing my site access on your dm.

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/44554636/188374170-59408c74-5a48-431b-a784-ddffe88b8595.png">

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/44554636/188373910-b09a01b3-5439-4cb8-8af6-a11f00bcd3be.png">

**Comment by aviral-mittal** [comment]
@abhishekfdd This is important and we should fix this asap.

**Comment by abhishekfdd** [comment]
@Rink9  Maybe you are checking at wrong url, if you have configured the Client ID detail for subsite bbpress then you should check it for that from here https://lutfun-rinky.rt.gw/bbpress/wp-admin

**Comment by Rink9** [comment]
@abhishekfdd I have setup for https://lutfun-rinky.rt.gw/ URL. 
If a user has one multisite and they setup only for main/parent site it should work with it's all subsite. If we have still to setup particularly for every subsite though it's multisite then how we are making this compatible with multisite?

Actual behaviour: Works only when particularly setup for subsites.
Expected behaviour: If we setup on main/parent site it should work with it's all subsites.

Please let me know if i am incorrect.

cc: @aviral-mittal

**Comment by abhishekfdd** [comment]
@Rink9  This plugin needs google client ID and  key, which will be unique for every domain so same key won't work for all the sites.

**Comment by Rink9** [comment]
@abhishekfdd Let's connect on a call and discuss about it. Somehow i am not able to connect though added Google client ID and key.

**Comment by Rink9** [comment]
@abhishekfdd As discussed on call mainly have to add  Client ID and Secrets from all the subsites. Also have to add all the subsites from google console. 
My confusion was if we add on parent site it will work on all the subsites but we have to add Client ID and Secrets individually from all the subsites then it will work. As in this use case Login-with-google is working.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/44554636/188834045-5ae8fabe-a080-473a-996f-71e5b97164b8.png">

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/44554636/188834567-d40209d7-5834-4cbb-8cdb-ed8ad59a38b3.png">

https://user-images.githubusercontent.com/44554636/188834347-a1a9f29e-0e3b-47bf-b0a1-765897ef1fcd.mov
