### ISSUE TITLE
Update Release Notes for all previous release tags

### ISSUE THREAD

**Issue by aviral-mittal** [rtCamp/login-with-google#128]
## Issue Description

Please update [release](https://github.com/rtCamp/login-with-google/releases) notes/changelog for all previous release tags by referring to the changelog [here](https://github.com/rtCamp/login-with-google/blob/master/readme.txt).

**Comment by Souptik2001** [comment]
@aviral-mittal Created release notes till `1.0.9`.

The tags from `1.0.9` to `1.0` doesn't have a wp.org release I guess, because `1.0.9` is marked as an initial release.
Therefore, didn't create a GitHub release for those lower versions as well.
