### ISSUE TITLE
The value of 'callback' is not a function

### ISSUE THREAD

**Issue by zandoga** [rtCamp/login-with-google#136]
When I inspect pages on my website ( 24digi.com ) with Chrome I find the two errors shown below. No errors on the Google login page and the login works fine otherwise.

[GSI_LOGGER]: The value of 'callback' is not a function. Configuration ignored.
_.z @ client:44
_.Em @ client:250
Tn @ client:286
fo @ client:290
(anonymous) @ client:361
(anonymous) @ client:361
(anonymous) @ client:380

client?ver=1665122255:44 [GSI_LOGGER]: The value of 'callback' is not a function. Configuration ignored.
_.z @ client?ver=1665122255:44
_.Em @ client?ver=1665122255:250
Tn @ client?ver=1665122255:286
fo @ client?ver=1665122255:290
(anonymous) @ client?ver=1665122255:361
(anonymous) @ client?ver=1665122255:361
(anonymous) @ client?ver=1665122255:380

**Comment by elifvish** [comment]
@ravid007
Issue flagged is not arising from the plugin.
A script with id login-with-google-one-tap-js which contains the necessary callback function is being lazy loaded on [24digi.com](http://24digi.com/)
Which results in console error. White listing this script from being lazy loaded should fix the issue.
cc: @aviral-mittal
