### ISSUE TITLE
Redirection to same page after successfull authentication is not working.

### ISSUE THREAD

**Issue by suraj-sanwal** [rtCamp/login-with-google#140]
Hi, 

I'm using the custom code suggested by @vishalkakadiya from here:
https://github.com/rtCamp/login-with-google/issues/95#issuecomment-1067945565

It was working fine till now but there is some issue with the ajax call which responding 0 after successfull authentication and redirecting customers to the url: https://www.site.com/wp-admin/admin-ajax.php 

![image](https://user-images.githubusercontent.com/54799210/210202493-58e827c8-819b-412e-b081-fdb187724c9b.png)

Can anyone please suggest the cause of the issue?

Thanks

**Comment by suraj-sanwal** [comment]
Hi @elifvish
Please give an update about the same ASAP as it's critical for us.
Thanks,

**Comment by elifvish** [comment]
Hi, @suraj-sanwal I looked into your issue. I tested the filter in a test site and it is working as expected. Please check if the issue mentioned is caused by some other plugin that was recently installed in your site.
cc: @aviral-mittal

**Comment by suraj-sanwal** [comment]
Okay. I'll check and get back to you. But as far as I concerned there is no any additional plugin was intalled in our site.
Anyways, Let me check once.

Thanks,

**Comment by suraj-sanwal** [comment]
Hi @elifvish 
The issue is with the custom code that I had wrote. I'm able to fix it now.
Thanks
