### ISSUE TITLE
the problem of arabic names

### ISSUE THREAD

**Issue by Hamzaanter** [rtCamp/login-with-google#141]
hi when i try to log in with google and the google name is in arabic it doesnt log me in and i dont know how to solve it really

**Comment by aviral-mittal** [comment]
@Hamzaanter As per our understanding - Google doesn't allow email IDs with Arabic characters. However, may be, your website is using another filter which may be inserting arabic characters in user name - which is not allowed by default in WordPress core. 

To allow arabic characters in username, may be you can try third-party plugins. 

Also, please note that the Arabic First Name and Last Name is allowed for users, however, usernames(for login purpose) with Arabic characters are not allowed in WordPress by default.
