### ISSUE TITLE
Feature Request - Login with JWT Auth

### ISSUE THREAD

**Issue by power-cut** [rtCamp/login-with-google#44]
I am powering my React mobile App with Wordpress REST API. I am using [JWT Auth](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/) Plugin to login and works great. WP JWT Auth plugin requires a password to get the token, now I want to integrate Google login.
Can this be a feature for this plugin ?

**Comment by ankitrox** [comment]
@power-cut Can you please explain the entire flow of the integration?

**Comment by ankitrox** [comment]
Closing this one as no further response received.
