### ISSUE TITLE
Add settings page 

### ISSUE THREAD

**Issue by juhi123** [rtCamp/login-with-google#45]
## Feature description
Add the settings page to add `client id`, `secret key`,  `whitelisted-domains`, whichever [we add in wp-config.php](https://github.com/rtCamp/wp-google-login#how-to-use-it)

---
## Acceptance criteria
1. Settings link should be given at plugins page
![Screenshot 2020-05-20 at 1 06 04 PM](https://user-images.githubusercontent.com/8724401/82418535-bcb76c80-9a9a-11ea-8c88-f35a425ea920.png)

2. Functionality shouldn't be affected

3. Give link to create project and credentials https://console.developers.google.com/apis/dashboard

**Comment by juhi123** [comment]
@itowhid06 Thanks for the PR :)
Can you please make a few minor changes to match with WP Core UI
1. Wrap the settings heading in `<div class="wrap">` 
![Screenshot 2020-06-05 at 12 30 11 PM](https://user-images.githubusercontent.com/8724401/83846525-584a0d80-a728-11ea-8818-eeb1adbc3aea.png)

2. Change `Here` to `here`  in this "If you do not have Project and Credentials, you can create one from Here". Also, I think it should be in `p` tag only

3. Use `<label for="client-id">Client ID</label>` for labels, refer general settings `wp-admin/options-general.php`. You will notice clicking on the label, it focuses the input field

4. For optional field instead of mentioning in it label, add description right below the input field like in general settings

**Comment by juhi123** [comment]
@itowhid06 Also add setting for user registration so this `define( 'WP_GOOGLE_LOGIN_USER_REGISTRATION', true );` also can be managed without adding in wp-config.php

**Comment by itowhid06** [comment]
@juhi123 All changes have been implemented.
