### ISSUE TITLE
403 error when login with google and normal log out

### ISSUE THREAD

**Issue by rahul286** [rtCamp/login-with-google#62]
@mrrobot47 when I try to login via the google login button I am getting nginx 403

1. You can go to https://hw.rsites.in/wp-login.php 
2. Try google login. It gives 403
3. Go to https://hw.rsites.in/wp-admin and you will be in
4. Try log out from WP top-right side profile menu, and 403 again

If this is not related to server config, then you may assign this to somebody from @rtCamp/developers

**Comment by kirtangajjar** [comment]
@rahul286 Can you check now? Looks like the issue was in the server config. We put 1req/s raet limit on `wp-login.php` and while logging out, two requests were sent to `wp-login.php` simultaneously, and secod one was causing 403.

![Screenshot from 2020-12-18 13-37-36](https://user-images.githubusercontent.com/8456197/102590450-9cd24f00-4136-11eb-9922-28c4f5e732bd.png)

**Comment by rahul286** [comment]
@mrrobot47 did we remove plugin

```The plugin login-with-google/wp-google-login.php has been deactivated due to an error: Plugin file does not exist.
```

Please add it from directory and configure it sitewide

**Comment by mrrobot47** [comment]
@rahul286 Did not remove the plugin. 
It was not active on network. Network activated now :white_check_mark:

**Comment by rahul286** [comment]
Still 403 https://hw.rsites.in/wp-login.php?loggedout=true&wp_lang=en_US

![403_Forbidden](https://user-images.githubusercontent.com/4115/102592915-32231280-413a-11eb-9a93-6dabc5750350.jpg)

**Comment by mrrobot47** [comment]
On which site did you get this error?

**Comment by mrrobot47** [comment]
@rahul286 please try now. The rate was set at 1 request per 6 second (`10r/m`). Eased it down to `1r/s`. Please check now.

**Comment by rahul286** [comment]
![rsites_in](https://user-images.githubusercontent.com/4115/102593998-a8744480-413b-11eb-8a58-9a3b4d1c4756.jpg)

**Comment by mrrobot47** [comment]
Did you get this just before my last message? Then probably Nginx restart caused it.
Please let me know if you get this again.

**Comment by rahul286** [comment]
Working now.
