### ISSUE TITLE
Remove duplicate DOM 

### ISSUE THREAD

**Issue by mehidi258** [rtCamp/login-with-google#67]
There is duplicate DOM element for unnecessary purpose. Ideally it should be removed. 
![image](https://user-images.githubusercontent.com/34313754/116608491-0f5d0200-a955-11eb-8382-f3d8bfa5f2d4.png)

**Comment by ankitrox** [comment]
https://github.com/rtCamp/login-with-google/pull/74

Will be resolved in the PR.
