### ISSUE TITLE
Feature Query/Request : Will it work with woocommerce?

### ISSUE THREAD

**Issue by underscore-network** [rtCamp/login-with-google#70]
Hi, can this work with Woocommerce by default or any tweaks needed for this to work?

**Comment by ankitrox** [comment]
@underscore-network `Login with Google` provides the ability to login/register using user's Google account. Prior version used to add Login button only in login form, but now you can also use shortcodes to insert `Login with google` button anywhere. 

Please refer the [shortcode doc](https://github.com/rtCamp/login-with-google/blob/master/README.md#shortcode) for further reference. For any other queries, please open a support ticket on [plugin's support forum](https://wordpress.org/support/plugin/login-with-google/).
