### ISSUE TITLE
How to translate it with Loco plugin?

### ISSUE THREAD

**Issue by mouveo** [rtCamp/login-with-google#75]
Hello,
great plugin!

There is this message : No translations found for "wp-google-login"

And when I create a translation, that doesn't work even if I changed the setup with a new template.

![loginwithgoogle](https://user-images.githubusercontent.com/9964910/121917586-8f88cc80-cd35-11eb-9525-11db31d34b11.png)

**Comment by ankitrox** [comment]
Thanks @mouveo,

Can you please update the plugin to version 1.1 and check if this resolves the issue for you?

I'm closing this issue here, if you need further support please consider opening support ticket on plugin's support forum on wordpress.org
