### ISSUE TITLE
Create Gutenberg Block for Google Login

### ISSUE THREAD

**Issue by rahul286** [rtCamp/login-with-google#77]
On similar lines we have for Github Login

**Comment by abhi3315** [comment]
@ankitrox What's the status of this issue? If it is not done then I can pick it up.

**Comment by aviral-mittal** [comment]
@abhishekfdd As discussed on call just now: 

1. - [ ] Change the button name to log out when logged in - no greying out needed. 
2. - [ ] Keeping the button size default as it can change size if used in a particular column, etc. User can add CSS class if custom size is required anywhere. 
3. - [ ] Show Google logo in the block in backend also - to keep in line with WYSWYG principle.

**Comment by aviral-mittal** [comment]
@abhishekfdd apart from the changes requested by Gagan, is there anything else remaining on this? Can we please have an ETA?

**Comment by aviral-mittal** [comment]
@abhishekfdd Let's aim to finish writing the pending test cases today so that this plugin release can go for testing.

**Comment by abhishekfdd** [comment]
@aviral-mittal Feedback changes and pending test case was done and is ready for review.

**Comment by abhishekfdd** [comment]
@aviral-mittal  This is merged now and ready for QA

**Comment by aviral-mittal** [comment]
QA - https://github.com/rtCamp/login-with-google/issues/121#issuecomment-1241887680
