### ISSUE TITLE
Disable Settings if Constants and Whitelisted domain are defined in wp-config file. 

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/login-with-google#79]
If we have constants and whitelisted domains defined in wp-config.php file then on adding whitelisted domain from field is not getting saved.

To avoid confusion we have to disable the fields from settings page if constants and whitelisted domains are defined in wp-config.php file. **note the data defined in wp-config.php file needs to be pre-filled and disabled**

If constants are not defined then show blank fields for users to add data in the fields.

**Comment by ankitrox** [comment]
@pooja-muchandikar Added this feature: https://stories.rtcamp.com/wp-admin/options-general.php?page=login-with-google

**Comment by ankitrox** [comment]
@pooja-muchandikar Can you please test and close this issue as it has been addressed already?

**Comment by pooja-muchandikar** [comment]
Have cross-checked the issue and following scenarios works fine. 

- If constants are defined in wp-config.php file then settings page fields appear disabled
- If constants are not defined in wp-config.php file then settings page fields appear enabled and can update domains and save successfully.

Closing this issue.
