### ISSUE TITLE
Support for One Tap User Experience

### ISSUE THREAD

**Issue by ankitrox** [rtCamp/login-with-google#82]
We can integrate One Tap Sign-In. We also have received a request in support forum for same:
https://wordpress.org/support/topic/support-google-one-tap-sign-in/

Reference for One tap sign-in: https://developers.google.com/identity/gsi/web/guides/features

**Comment by pooja-muchandikar** [comment]
@ankitrox 

Cross-checked one tap login feature and functionality wise works fine.  
<img width="1255" alt="Screenshot 2021-07-15 at 3 38 20 PM" src="https://user-images.githubusercontent.com/41000648/125770798-48ec182c-c400-4b70-a9a3-da3e178e7906.png">

---

But while checking its settings found one issue: Enable One Tap Login Only on Login Screen the feature is not working as the per the option enabled. 

For ex: I enabled Enable One Tap Login Only on Login Screen option this option should only show the One tap login option on Login Screen right but its showing on all pages like homepage, single page etc. Refer the visual: https://drive.google.com/file/d/1bqVUAZI-E-f-5XspdTq912Kuf-vMeSo6/view
