### ISSUE TITLE
If change url wp-login can't use plugin

### ISSUE THREAD

**Issue by napathello** [rtCamp/login-with-google#88]
Hello

We use custom url on login block spam and brute force attack
But we click login with google have error

https://dropover.cloud/24d4fd

**Comment by ankitrox** [comment]
@napathello Can you please confirm what is the URL for login in WordPress and what it is in Google Console?

**Comment by napathello** [comment]
@ankitrox hello my setting url in console same in wordpress
Use /my-login/
https://dropover.cloud/d5c98b

**Comment by vishalkakadiya** [comment]
@napathello Can you share which plugin you are using for changing the admin area's URL or any other manual configuration you did for changing the admin URL?

**Comment by MoryCorp** [comment]
Hi, I have the same issue with this plugin : https://fr.wordpress.org/plugins/wps-hide-login/  
I set the login page to https://mydomain.com/login
Setting the direct to https://mydomain.com/login on Google Cloud and getting an error
